require "rspec"
require "rspec/core/rake_task"

coverage_dir = File.expand_path(File.join(File.dirname(__FILE__), "coverage"))

RSpec::Core::RakeTask.new do |t|
  t.pattern = "*_spec.rb"
  t.rspec_opts = ["--format", "documentation", "--colour"]
end

desc "Run specs using RCov"
RSpec::Core::RakeTask.new("spec:rcov") do |t|
  t.pattern = "*_spec.rb"
  t.rspec_opts = []
  t.rcov = true
  t.rcov_opts = %W{--exclude osx\/objc,gems\/,spec\/,features\/ -o "#{coverage_dir}"}
end
